# -*- coding: utf-8 -*-
"""final_text_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtIUM53V0sAceYyDhjDZxppOlQUVYyUx
"""

# Mount your Google Drive to save outputs
from google.colab import drive
drive.mount('/content/drive')

# Define output directory
import os
save_dir = "/content/drive/MyDrive/hyigiea/data/Hinglish_Empathy_Dataset"
os.makedirs(save_dir, exist_ok=True)
print(f"output directory: {save_dir}")

!pip install transformers torch nltk indic-nlp-library langdetect tqdm

!pip install transformers accelerate bitsandbytes sentencepiece

from huggingface_hub import login
login(token_hf)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-7B-Instruct"

tok = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

print("Model loaded:", model_name)

def generate_dialogue(topic="self_doubt", turns=2):
    system_prompt = (
        "You are an empathetic Indian mental-health counselor. "
        "Speak in natural Hinglish (Hindi mixed with English). "
        "Be warm, concise, non-judgemental."
    )

    user_prompt = (
        f"Generate a {turns}-turn counselling dialogue about '{topic}'. "
        "Format:\nClient: …\nTherapist: …\nClient: …\nTherapist: …\n"
        "Make it sound like real Indian conversation."
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    inputs = tok.apply_chat_template(messages, return_tensors="pt").to(model.device)

    output = model.generate(
        inputs,
        max_new_tokens=150,
        temperature=0.8,
        top_p=0.9,
        do_sample=True,
        repetition_penalty=1.11,
        eos_token_id=tok.eos_token_id,
    )

    text = tok.decode(output[0], skip_special_tokens=True)

    # cut everything before the assistant’s turn
    if "assistant" in text:
        text = text.split("assistant")[-1].strip()

    return text.strip()

def clean_dialogue(d):
    if "Client:" not in d or "Therapist:" not in d:
        return None
    if len(d.split()) < 30:
        return None
    bad = ["Breaking News", "Article", "Views", "Comments", "###"]
    if any(b in d for b in bad):
        return None
    return d

import os, json, random
from tqdm import tqdm

num_dialogues = 2000
batch_size = 200

topics = [
    "self_doubt", "loneliness", "anxiety", "academic_pressure",
    "relationship_issues", "family_conflict", "career_confusion",
    "burnout", "financial_stress", "fear_of_failure"
]

save_dir = "/content/drive/MyDrive/hygieia/data/Qwen2.5_Hinglish_Empathy"
os.makedirs(save_dir, exist_ok=True)

for start in range(0, num_dialogues, batch_size):
    end = min(start + batch_size, num_dialogues)
    batch_data = []

    for i in tqdm(range(start, end)):
        topic = random.choice(topics)

        dialogue = None
        while dialogue is None:
            raw = generate_dialogue(topic)
            dialogue = clean_dialogue(raw)

        batch_data.append({
            "id": i + 1,
            "topic": topic,
            "dialogue": dialogue
        })

    out = os.path.join(
        save_dir,
        f"hinglish_dialogues_part_{start//batch_size + 1}.jsonl"
    )

    with open(out, "w", encoding="utf-8") as f:
        for entry in batch_data:
            json.dump(entry, f, ensure_ascii=False)
            f.write("\n")

    print("Saved batch:", start//batch_size + 1)